name: Run Script Daily

on:
  schedule:
    - cron: "0 10 * * *"  # Runs every day at 10:00 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'  # Change this to your Python version

      - name: Install dependencies
        run: |
          pip install opencv-python requests

      - name: Run the script
        run: python main.py  # Replace with your script filename
